Change VPBuildVersion to DOUBLE and return GIT_REVISION as decimal #1558
vpinball/vpinball pull request #1850
Opened 2024-07-19 09:04 UTC by JockeJarre

I have now reactivated VPBuildVersion (it was stated to be deprecated) but have changed it to return a double instead of integer.
The git build number is now the decimal of the returned value.

2024-07-19 16:20 UTC, toxieainc commented
@jsm174 @vbousquet Any issues with this? Looks fine to me like this..

2024-07-29 20:57 UTC, vbousquet requested changes
I don't see any problem with the proposed change.
To be more consistent with other uses of float & double in IDL and implementation, I think this should use `double` instead of `DOUBLE`
Also, when computing the value, this should use double value and not float

2024-07-29 20:57 UTC, vbousquet commented on src/parts/pintable.cpp
> +   *pVal = VP_VERSION_MAJOR * 1000 + VP_VERSION_MINOR * 100 + VP_VERSION_REV + GIT_REVISION / 10000.0f;
Use `10000.0` instead of `10000.0f`

2024-07-29 22:36 UTC, jsm174 commented
I'm guessing I will need to regen the IDL for standalone, so I can either tack on when this is ready, or just add a new commit.

2024-07-30 19:38 UTC, merged

2024-07-30 19:38 UTC, toxieainc commented
Thanks all!

2024-07-30 20:41 UTC, toxieainc commented
@JockeJarre One more thing: I would propose to divide by 100000, maybe even 1000000, instead of 10000. Seems to be more future proof for now.

2024-07-30 21:00 UTC, jsm174 commented
@JockeJarre / @toxieainc ,

Was just thinking about this:

`VPBuildVersion - same as Version but with the github build number as decimal (GIT_REVISION / 10000.0)`

I know for myself, when building manually during dev, I never have `GIT_REVISION` set. Guessing this shouldn't be a issue.

2024-07-30 21:07 UTC, toxieainc commented
Yes, i don't think so. Unless one would test a very specific table that checks for this.

2024-07-31 05:46 UTC, JockeJarre commented
> One more thing: I would propose to divide by 100000, maybe even 1000000, instead of 10000. Seems to be more future proof for now.

@toxieainc Wouldn't it be better if we make the counter start from 1 for a new release? Normally 9999 would for sure be enough? We also have statements like `fprintf(f, "%04X", GIT_REVISION);` in the code. So we do not expect it to exceed 9999.


> I know for myself, when building manually during dev, I never have `GIT_REVISION` set. Guessing this shouldn't be a issue.

@jsm174 we could set the "default" value in the source to 9999 when you compile locally. When testing tables, your local build will always be newer than those checked in.

2024-07-31 06:26 UTC, toxieainc commented
I'd hope 9999 would be enough, too, but we're already pretty high right now..  :)

2024-07-31 06:56 UTC, JockeJarre commented
Yes, you are right. 20% is used soon. But we need to make 10.8.1 start from 1, which @jsm174 already has prepared for. We need to update the hash number in the build script

2024-07-31 07:24 UTC, JockeJarre commented
> Yes, you are right. 20% is used soon. But we need to make 10.8.1 start from 1, which @jsm174 already has prepared for. We need to update the hash number in the build script

But with 10.8.1 it is already to late, it is using the same counter as 10.8.0... It could be solved by moving to 10.8.2 soon and reset the counter hash (VERSION_START_SHA)